
## Clustering:  Thickness

```{r,results = 'asis', echo = T}
results <- read.csv( './Data/labelresultsAntsSubset.csv' )
resultsThickness <- results[, grep('^thickness.', names( results ) )]
resultsThickness <- resultsThickness[complete.cases( resultsThickness ),]


for( numberOfClusters in 2:20 )
  {
  nick <- pam( resultsThickness, numberOfClusters, metric = "manhattan" );
  cat( "nclusters = ", i, " -> ", nick$silinfo$avg.width, "\n", sep = '')
  }

# for( i in 1:ncol( resultsThickness ) )
#  {
#  resultsThickness[,i] <- resultsThickness[,i] / results$total.mean.thickness[i]
#  }
# km <- kmeans( resultsThickness, 3, 15 )


# plot clusters
# pdf( "~/Desktop/clusterThickness.pdf", width = 100, height = 25)
# plot( resultsThickness, col = km$cluster )
# points( km$centers, col = 1:2, pch = 8 )
# dev.off()

# hc <- hclust( dist( resultsThickness ) )
# pdf( "~/Desktop/clusterThickness.pdf", width = 100, height = 25)
# plot( hc, labels = results$dx.group, hang = -1 )
# dev.off()
```








## Clustering:  Jacobian

```{r,results = 'asis', echo = F}
results <- read.csv( './Data/labelresultsAntsSubset.csv' )
resultsJacobian <- results[, grep('^jacobian.', names( results ) )]
hc <- hclust( dist( resultsJacobian ) )
pdf( "~/Desktop/clusterJacobian.pdf", width = 100, height = 25)
plot( hc, labels = results$dx.group, hang = -1 )
dev.off()
```
